language: ruby

cache: bundler

sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2

matrix:
  include:
    test_isolated

matrix:
  include:
    - script: bundle exec rake test_isolated

notifications:
  email: false
