language: ruby

cache: bundler

sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.1

matrix:
  include:
    test_isolated

matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/Gemfile-1.9
    - rvm: 2.2
      script: bundle exec rake test_isolated

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "bJyiK4EXGfm0EhAId/QqIEdhPCx8BjxUKvx1h0+wgrsUm8BDoEN7tg2wqoGWU2KfzqLdx77wZVQXbmksOgmNcMGKJed5uNNMpAG4B+AQYTEX0odFRgOZKdkMtypga9CNIkKVgeSKhd6BY+g2AV6wvJ0Jq056uXpGkqK5OEFOpQc="
